version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm run test      
  
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
      - run: npm audit 

workflows:
  build-test-analyze-workflow:
    jobs:
      - build
      - test:
          requires:
          - build
      - analyze:
          requires:
          - test
#
